kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
    name: blog-build
    labels:
        app: blog
spec:
    output:
        to:
            kind: ImageStreamTag
            name: 'blog:latest'
    source:
        type: Git
        git:
            uri: "https://github.com/sousamleonardo/blog" 
        contextDir: /
        
    strategy:
        type: Docker
        dockerStrategy:
            dockerfilePath: Dockerfile

    triggers:
    - type: GitHub
      github:
        secret: secret101
    - type: ConfigChange
    - type: ImageChange